#!/usr/bin/env bash


parse_ctx()
{
	local fl=$1

	[ -z "$fl" ] && echo "usage $0 filename" && exit 1

	_get_utf8_ctx()
	{
		file $fl | grep -iq "utf-8" && {
			cat $fl
		} || {
			cat $fl | iconv -c -f gbk -t utf8 
		}
	}

	_get_utf8_ctx | awk -f gettitle.awk
	_get_utf8_ctx | sed -n -f getctx.sed | sed  's/<.*>//g'

#	cat $fl | iconv -f gbk -t utf8 | awk -f gettitle.awk
#	cat $fl | iconv -f gbk -t utf8 | sed -n -f getctx.sed | sed  's/<.*>//g'
	echo ""
	echo ""
}

[ `basename $0` == fetchctx ] && parse_ctx $*

