#!/bin/sh


[ $# -lt 1 ] && echo "missing opt" && exit 1


install_ems()
{
	local root
	root=/usr/ems

	mkdir -p $root
	cp -rf bin  $root
	cp -rf conf $root

	chmod u+x $root/bin/ems
	chmod u+x $root/bin/app_setup.sh

	cp -f $root/conf/emsd /etc/init.d/emsd

	ln -sf ems $root/bin/ems_bwlist
	ln -sf ems $root/bin/ems_fw
	ln -sf ems $root/bin/ems_c
	ln -sf ems $root/bin/ems_wireless
	ln -sf ems $root/bin/ems_config
	ln -sf ems $root/bin/ems_ls
	ln -sf ems $root/bin/ems_network
	ln -sf ems $root/bin/ems_status

	chmod u+x /etc/init.d/emsd

	# update version info
	echo "$(grep "app.version" appinfo | awk -F= '{print $2}')">$root/conf/ver

	/etc/init.d/emsd start

	return 0
}


case $1 in 
	install)
		shift
		install_ems
	;;

	*)
		echo "unknown opt"
		exit 1
	;;
esac
