#!/bin/bash

array=(one two three four     [5]=five)

echo "Array size: ${#array[*]}"

echo "Array  items: ${array[@]}  ---> ${array[*]}"
#for item in ${array[*]}

echo "Array items:"
for item in ${array[*]}
do
	printf "   %s\n" $item
done

echo "Array indexes:"
for index in ${!array[*]}
do
	printf "   %d\n" $index
done

echo "Array items and indexes:"
for index in ${!array[*]}
do
	printf "%4d: %s\n" $index ${array[$index]}
done



e=${array[@]}

echo "$a, $b, $c, $d, $e"

e=${array[*]}

echo "$a, $b, $c, $d, $e"



array=("first item" "second item" "third" "item")

echo "Number of items in original array: ${#array[*]}"
for ix in ${!array[*]}
do
	printf "   %s\n" "${array[$ix]}"
done
echo

arr=(${array[*]})
echo "After unquoted expansion: ${#arr[*]}"
for ix in ${!arr[*]}
do
	printf "   %s\n" "${arr[$ix]}"
done
echo

arr=("${array[*]}")
echo "After * quoted expansion: ${#arr[*]}"
for ix in ${!arr[*]}
do
	printf "   %s\n" "${arr[$ix]}"
done
echo

arr=("${array[@]}")
echo "After @ quoted expansion: ${#arr[*]}"
for ix in ${!arr[*]}
do
	printf "   %s\n" "${arr[$ix]}"
done
